Repository torchbox/wagtail-grapple, pull requests merged in 2020-10, with the labels that each got.

#105 Update supported versions
  example/example/tests/test_grapple.py
  grapple/actions.py
  grapple/types/documents.py
  grapple/types/images.py
  grapple/types/media.py
  requirements.txt
  setup.cfg
Labels: Status: Ready To Review, Type: Chore

#122 Add embed data for StreamField Embed blocks
  example/example/settings/base.py
  example/example/tests/test_grapple.py
  example/home/test/test_blog.py
  grapple/types/streamfield.py
Labels: Status: Ready To Review, Type: Feature

#124 Add GraphQLTag model
  docs/general-usage/model-types.rst
  example/home/factories.py
  example/home/migrations/0017_auto_20201006_2147.py
  example/home/models.py
  example/home/test/test_blog.py
  grapple/models.py
  grapple/schema.py
  grapple/types/tags.py
Labels: Status: Ready To Review, Type: Feature

#106 Make wagtailmedia an optional dependency
  grapple/actions.py
  grapple/schema.py
  grapple/types/pages.py
Labels: Status: In Progress, Type: Chore

#115 Multi-site support - add SitesQuery and resolve pages based on site
  docs/general-usage/graphql-types.rst
  example/example/tests/test_grapple.py
  grapple/schema.py
  grapple/types/pages.py
  grapple/types/sites.py
Labels: Status: Ready To Review, Type: Feature

#127 Fix parent attribute
  example/example/tests/test_grapple.py
  grapple/types/pages.py
Labels: Status: Ready To Review, Type: Hotfix

#129 Add .live().public() to all relevant methods
  grapple/types/pages.py
Labels: Status: Ready To Review, Type: Hotfix

#130 Add webpquality support for renditions
  docs/general-usage/graphql-types.rst
  example/images/models.py
  grapple/types/documents.py
  grapple/types/images.py
  grapple/types/media.py
  grapple/types/pages.py
  grapple/types/streamfield.py
  grapple/types/tags.py
Labels: Status: Ready To Review, Type: Feature

#132 Add hook for registering query mixins
  docs/general-usage/hooks.rst
  docs/general-usage/index.rst
  grapple/schema.py
  grapple/wagtail_hooks.py
Labels: Status: In Progress, Type: Feature

#133 Fix StubModel already registered RuntimeWarning
  grapple/actions.py
  grapple/migrations/0004_delete_stubmodel.py
Labels: Status: Ready To Review, Type: Hotfix
