Repository torchbox/wagtail-grapple, pull requests merged in 2020-11, with the labels that each got.

#136 Bump Python versions
  .github/workflows/pre-commit.yml
  .github/workflows/tests.yml
  .pre-commit-config.yaml
  README.md
  example/Dockerfile
  example/home/migrations/0017_auto_20201006_2147.py
  grapple/migrations/0004_delete_stubmodel.py
  setup.cfg
Labels: Status: Ready To Review, Type: Feature

#135 Bump Wagtail versions documentation
  README.md
  requirements-channels.txt
Labels: Status: Ready To Review, Type: Chore

#140 Use the correct type prefix with register_media_model
  grapple/actions.py
Labels: bug
