Repository torchbox/wagtail-grapple, pull requests merged in 2021-07, with the labels that each got.

#174 docs: schema mutation subscription hooks
  .github/workflows/ci.yml
  docs/general-usage/hooks.rst
  example/example/tests/test_grapple.py
  example/home/mutations.py
  example/home/subscriptions.py
  example/home/test/test_general.py
  example/home/test/test_subscriptions.py
  example/home/wagtail_hooks.py
Labels: documentation

#155 Add hooks for registering mutation and subscription mixins
  .github/workflows/ci.yml
  docs/general-usage/hooks.rst
  example/example/tests/test_grapple.py
  example/home/mutations.py
  example/home/subscriptions.py
  example/home/test/test_general.py
  example/home/test/test_subscriptions.py
  example/home/wagtail_hooks.py
  grapple/schema.py
  grapple/wagtail_hooks.py
Labels: Status: Ready To Review, Type: Feature

#176 ci: run tests on multiple wagtail versions
  .github/workflows/ci.yml
  example/documents/migrations/0001_initial.py
  example/example/settings/base.py
  example/example/tests/test_grapple.py
  example/home/migrations/0002_create_homepage.py
  example/home/models.py
  example/home/test/test_blog.py
Labels: Status: Ready To Review, Type: Chore

#175 feat: single settings GRAPPLE support
  README.md
  docs/general-usage/decorators.rst
  docs/general-usage/graphql-types.rst
  docs/general-usage/index.rst
  docs/general-usage/settings.rst
  docs/getting-started/installation.rst
  example/example/settings/base.py
  example/example/tests/test_grapple.py
  example/example/tests/test_settings.py
  example/home/test/test_blog.py
  example/home/test/test_general.py
  grapple/actions.py
  grapple/helpers.py
  grapple/schema.py
  grapple/settings.py
  grapple/templates/grapple/graphiql.html
  grapple/types/images.py
  grapple/types/structures.py
  grapple/urls.py
  grapple/utils.py
Labels: Status: Ready To Review, Type: Feature, documentation

#177 feat: add middleware support for queries
  README.md
  docs/general-usage/decorators.rst
  docs/general-usage/hooks.rst
  docs/general-usage/index.rst
  docs/general-usage/middleware.rst
  docs/general-usage/model-types.rst
  docs/general-usage/preview.rst
  docs/general-usage/settings.rst
  docs/getting-started/examples.rst
  docs/getting-started/installation.rst
  docs/index.rst
  example/example/settings/base.py
  example/example/tests/test_grapple.py
  example/home/models.py
  example/home/test/test_advert.py
  example/home/test/test_blog.py
  example/home/test/test_general.py
  grapple/actions.py
  grapple/helpers.py
  grapple/middleware.py
  grapple/registry.py
Labels: Status: Ready To Review, Type: Feature
